apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-deployment
  labels:
    app: nest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest
  template:
    metadata:
      labels:
        app: nest
    spec:
      containers:
        - name: nest
          image: windsnow1025/coms6998-nest:test
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: ENV
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: POSTGRES_HOST
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_DB
            - name: S3_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: S3_HOST
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: S3_SECRET_KEY
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: S3_BUCKET_NAME
            - name: S3_WEB_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: S3_WEB_URL
  revisionHistoryLimit: 0